### ISSUE TITLE
Color picker

### ISSUE THREAD

**Issue by zrispo** [zrispo/wick#148]
Here's a nice one:

http://jscolor.com/

We need to replace the one we're using right now (the html5 color picker) because it pretty much only works on chrome from what I've tested Wick on.

**Comment by joshrispoli** [comment]
https://github.com/zrispo/wick/commit/9375940e3dde957b8b7176b27a3ad679ad321224

Switched to jscolor- works for paintbrush tool only (text tool currently freaking out)
