### ISSUE TITLE
Scripting IDE error handling (so project wont run till u fix errors)

### ISSUE THREAD

**Issue by joshrispoli** [zrispo/wick#15]
The editor should have an IDE for the scripting system.  We must support:

- Error handling (Project won't run until you fix all the errors)
- Highlighting wick reserved words (i.e. onLoad)
- More wick features that we haven't thought of yet

**Comment by zrispo** [comment]
j's workin on this things are looking good

**Comment by zrispo** [comment]
https://ace.c9.io/#embedding=&nav=higlighter

**Comment by zrispo** [comment]
important: http://stackoverflow.com/questions/9781285/specify-scope-for-eval-in-javascript

**Comment by zrispo** [comment]
**update**

have a working ide !!!!!!!!
we still must do syntax error handling - project dont run till u fix errors - but how ??
-zach
