### ISSUE TITLE
This GIF of a bee crashes wick

### ISSUE THREAD

**Issue by zrispo** [zrispo/wick#228]
![beetoon](https://cloud.githubusercontent.com/assets/4970417/19816120/ff049cc6-9d13-11e6-98f2-3d79673ca487.gif)

**Comment by zrispo** [comment]
(this is not a joke, try it)

**Comment by zrispo** [comment]
haha just realized that this is a 'bug' get it

**Comment by kryptot7** [comment]
Still happens in 0.4! 😱

**Comment by zrispo** [comment]
Still happens to this day.................... and I still have no idea why........

**Comment by Luxapodular** [comment]
Ah yes, the cursed bee...

**Comment by zrispo** [comment]
Yeh so there's this nasty code in `libgif.js` that does this thing:

![screen shot 2017-09-30 at 10 37 55 pm](https://user-images.githubusercontent.com/4970417/31051208-0a457a76-a630-11e7-95b3-024efda8fa2f.png)

So yeah I guess a `while(true)` is a lil dangerous. I jammed a break in there so it works for that bee gif:

![screen shot 2017-09-30 at 10 38 52 pm](https://user-images.githubusercontent.com/4970417/31051214-31ef2ca2-a630-11e7-984d-20ca85654605.png)

This might cause problems later on down the line. But at least we can import this bee now.
