### ISSUE TITLE
Selecting an object in the "back" (low z-order) will make it appear to be in the front in the editor. 

### ISSUE THREAD

**Issue by Luxapodular** [zrispo/wick#249]
A fabric thing that we need to override.

**Comment by zrispo** [comment]
Fixed for now, but occasionally this bug comes up:

https://github.com/kangax/fabric.js/issues/3095

Moving to new version of fabric will fix this (i think)

**Comment by zrispo** [comment]
Here was the problem:
https://github.com/kangax/fabric.js/issues/148
