### ISSUE TITLE
Can't zoom/resize website on mobile

### ISSUE THREAD

**Issue by hugs** [zrispo/wick#311]
## Problem
The viewport tag on several pages disables zooming and thus makes the site hard to use on mobile devices.

The specific line is causing the problem:

    <meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">

## Solution

Remove the meta viewport tag. It appears in the following files:
  -  index.html
  - sitepages/about.html
  - sitepages/reference.html
  - sitepages/resources.html
  - sitepages/submit.html
  - sitepages/tutorials.html
  - sitepages/walloftesters.html

## Discussion

See this thread on Hacker News: https://news.ycombinator.com/item?id=13245179

## Testing
(Tested on Nexus 6P, Android 7.1.1)

### Before Fix
<img src="https://cloud.githubusercontent.com/assets/8536/21462169/530b21ec-c91e-11e6-8dd1-f8356773095c.png" alt="before-fix" width="400 px"/>

<hr/>

### After  #Fix
<img src="https://cloud.githubusercontent.com/assets/8536/21462168/5309ebba-c91e-11e6-8e4c-cdd0aa9e48ab.png" alt="after-fix" width="400 px"/>

<hr/>

**Comment by hugs** [comment]
Fixed by PR #312

**Comment by zrispo** [comment]
Hey! Thanks for the PR ~

**Comment by hugs** [comment]
Wow, that was fast! You're welcome. :-) Thanks again for the awesome project!
