### ISSUE TITLE
Feature Restriction

### ISSUE THREAD

**Issue by Immortalin** [zrispo/wick#313]
What is the best way to restrict the features of wick? E.g. if you only want the static abilities i.e. no animations etc. which file should one edit? Is it sufficient to simply change the UI file?

**Comment by zrispo** [comment]
It'd probably be easiest to just take stuff out of the GUI. The way most of the GUI works is kind of a mess currently though, you might have to dig through the nastiness in `editor.html` ... 

What are you planning on working on? I might be able to help out

**Comment by Immortalin** [comment]
@zrispo what I am working on is pretty simple. A gift card builder where you add your greetings to a stock photo. Nothing more than a glorified meme builder really. I originally wanted to use darkroomjs for the image editing part but the lack of text/captioning abilities makes it unfeasible. Been hoping to get it out before Xmas but guess it's too late now ;(
