### ISSUE TITLE
first frame issues

### ISSUE THREAD

**Issue by molleindustria** [zrispo/wick#322]
The first frame seems to behave weirdly, the brush "scales down" once the stroke is completed and creating a new project doesn't clear all the shapes.
Here's a gif
http://giphy.com/gifs/26xBAa1TpgsDZNOZa
Chrome browser.

Good job, really impressive project!

**Comment by zrispo** [comment]
Looks like I forgot to test stuff on retina displays again -_-

Will push a fix for this tonight ~~
