### ISSUE TITLE
projects with tweens won't play when saved as .html

### ISSUE THREAD

**Issue by pepemont** [zrispo/wick#356]
html-embedded player is different from editor player : "Uncaught ReferenceError: WickTween is not defined"

**Comment by zrispo** [comment]
Found the problem,

in the project exporter (`WickProject.Exporter.js`), `WickTween.js` isn't included in the list of files to be bundled with the project to export. So the builtin player had access to the WickTween class, but exported projects didn't.

**Comment by zrispo** [comment]
Thanks for the bugfinding  ~~~

**Comment by pepemont** [comment]
Thanks for the quick fix ! This project is just amazing !
