### ISSUE TITLE
Design and Implement "Timeline Tools" Editor Panel

### ISSUE THREAD

**Issue by Luxapodular** [zrispo/wick#366]
What tools belong in the timeline and not in the action palette? 

Where do they go?

**Comment by Luxapodular** [comment]
Possible tools:

 - Onion skin toggle
 - Zoom / Box toggle

etc.

**Comment by Luxapodular** [comment]
+5

**Comment by Luxapodular** [comment]
Some actions have been moved to action palette, see action palette issue.

**Comment by supercgeek** [comment]
- [ ] Setting to view 'time' on the timeline (i.e. do you toggle on a calculation of time-passed based on framerate).
