### ISSUE TITLE
What does the timeline look like when...

### ISSUE THREAD

**Issue by Luxapodular** [zrispo/wick#370]
Child Components

- [ ] 1. Drag Frame(s) - On Layer / Between Layers 
- [ ] 2. Extend/Shrink Frame 
- [ ] 3. Select Frame(s) 
- [ ] 4. Adding Scripts to Frames
- [ ] 5. Displaced Frames - Null Frames Between Frames
- [ ] 6. Empty Frame vs Full Frame
- [ ] 7. Playhead
- [ ] 8. Preview Mode for Projects
- [ ] 9. States vs. Frames
- [ ] 10. Add New Frames to Timeline 
- [ ] 11. Deleting Frames
- [ ] 12. Zooming on the Timeline
- [ ] 13. Copy/Cut/Paste Frames 
- [ ] 14. Scrolling through frames
- [ ] 15. Layer Interactions on the Timeline

**Comment by Luxapodular** [comment]
+13

**Comment by Luxapodular** [comment]
Child Components
1. Drag Frame(s) - On Layer / Between Layers 
2. Extend/Shrink Frame 
3. Select Frame(s) 
4. Adding Code to Frames
5. Displaced Frames - Null Frames Between Frames
6. Empty Frame vs Full Frame
7. Playhead
8. Preview Mode for Projects
9. States vs. Frames

**Comment by supercgeek** [comment]
![artboard 6 copy](https://cloud.githubusercontent.com/assets/5409755/22962934/1b7cd868-f31e-11e6-93a8-81e0d5ee068f.png)

**Comment by supercgeek** [comment]
![artboard 6 copy](https://cloud.githubusercontent.com/assets/5409755/22962969/3a4e422c-f31e-11e6-90df-dbfec3059ab1.png)

**Comment by supercgeek** [comment]
![artboard 6 copy](https://cloud.githubusercontent.com/assets/5409755/22962986/518b9aac-f31e-11e6-8df2-8c8656215047.png)
