### ISSUE TITLE
Implement Backend Timeline Framework

### ISSUE THREAD

**Issue by Luxapodular** [zrispo/wick#380]

**Comment by Luxapodular** [comment]
+8

**Comment by zrispo** [comment]
![16706733_1625772840773459_863600681_n](https://cloud.githubusercontent.com/assets/4970417/22853580/991bbc2e-f028-11e6-9d41-2834b22e47f4.jpg)

For future reference -

**Comment by zrispo** [comment]
![screen shot 2017-02-13 at 2 10 43 am](https://cloud.githubusercontent.com/assets/4970417/22874059/fa416854-f191-11e6-8ead-1e048ec8fe62.png)

**Comment by zrispo** [comment]
Here's a few in-progress gifs demonstrating mouse interactions with the timeline:

**Dragging frames around:**
![timeline1](https://cloud.githubusercontent.com/assets/4970417/23003918/a7b6ef5a-f3c1-11e6-968a-2b893d093a22.gif)

**Stretching frames out:**
![timeline2](https://cloud.githubusercontent.com/assets/4970417/23003917/a7b5e042-f3c1-11e6-9086-148d94392443.gif)

**Moving layers and moving frames across layers:**
![timeline3](https://cloud.githubusercontent.com/assets/4970417/23003919/a7bac3a0-f3c1-11e6-9edd-65d0bb20df3a.gif)

**Highlighting frames by clicking and by dragging a selection box:**
![timeline4](https://cloud.githubusercontent.com/assets/4970417/23003916/a7b5df02-f3c1-11e6-82f9-6729920fd054.gif)
