### ISSUE TITLE
Adding New Frames to the Timeline 

### ISSUE THREAD

**Issue by Luxapodular** [zrispo/wick#388]
In what ways can a user add new frames to the timeline and what should it look like when they do?

**Comment by GautamBose** [comment]
![screen shot 2017-02-15 at 1 04 20 am](https://cloud.githubusercontent.com/assets/8022792/22962464/e068346e-f31a-11e6-8b90-7a96ca4608f9.png)
![screen shot 2017-02-15 at 1 04 56 am](https://cloud.githubusercontent.com/assets/8022792/22962469/e7ad8e36-f31a-11e6-819d-96c3e37f4769.png)

Explorations for adding new Frames
