### ISSUE TITLE
Layers on the Timeline

### ISSUE THREAD

**Issue by Luxapodular** [zrispo/wick#389]
- [ ] How do we add layers? 
- [ ] How do we remove layers? 
- [ ] How do I know what layer is selected? 
- [ ] What other interactions can I have with layers? [i.e. Locking/Ghosting]

**Comment by zrispo** [comment]
<img width="698" alt="screen_shot_2017-03-01_at_8 08 14_pm" src="https://cloud.githubusercontent.com/assets/4970417/23524536/1bd41f96-ff59-11e6-83fd-b913429f5226.png">
