### ISSUE TITLE
Drawings get very large after first being drawn.

### ISSUE THREAD

**Issue by Luxapodular** [zrispo/wick#39]
When drawing with the basic pencil tool, lines get huge after releasing the mouse.

**Comment by zrispo** [comment]
This only happens on specific browsers/OSes but I don't know which ones.

**Comment by zrispo** [comment]
what u usin bb

**Comment by Luxapodular** [comment]
Tested in Safari, Firefox and Chrome.

**Comment by zrispo** [comment]
Windows?

**Comment by Luxapodular** [comment]
Mac

**Comment by zrispo** [comment]
uh oh

**Comment by Luxapodular** [comment]
Get on Video, I'll show ya

**Comment by zrispo** [comment]
https://gist.github.com/jbergantine/2114328

found dis issue. retinal displays double the size of images because they have pixels that are like bigger or whatever
