### ISSUE TITLE
Action Palette Discussion and Development

### ISSUE THREAD

**Issue by Luxapodular** [zrispo/wick#390]
What does the "action palette" need and how does it work?

**Comment by GautamBose** [comment]
![screen shot 2017-02-15 at 12 59 37 am](https://cloud.githubusercontent.com/assets/8022792/22962600/d1dcc9c2-f31b-11e6-8c64-9ddc97581eb2.png)
![screen shot 2017-02-15 at 1 01 10 am](https://cloud.githubusercontent.com/assets/8022792/22962587/b9a154a4-f31b-11e6-93b7-203e40be2c19.png)
![screen shot 2017-02-15 at 1 12 55 am](https://cloud.githubusercontent.com/assets/8022792/22962611/e54a9728-f31b-11e6-8060-2dc9f37a959a.png)
![screen shot 2017-02-15 at 1 00 38 am](https://cloud.githubusercontent.com/assets/8022792/22962630/110ad88c-f31c-11e6-8903-19fb42e5ec20.png)
![screen shot 2017-02-15 at 1 00 26 am](https://cloud.githubusercontent.com/assets/8022792/22962633/19df9038-f31c-11e6-80b0-e3a772b6e2f1.png)


![screen shot 2017-02-15 at 1 02 20 am](https://cloud.githubusercontent.com/assets/8022792/22962589/be27f096-f31b-11e6-834c-bc34e4de93fe.png)
