### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by zrispo** [zrispo/wick#4]
![13220085_1354153361268743_1616363555_n](https://cloud.githubusercontent.com/assets/4970417/15346980/0eae2868-1c8b-11e6-8e9c-c77b9e7de194.jpg)

**Comment by zrispo** [comment]
Implemented!

Player needs to be updated though

**Comment by chaoyuedajun** [comment]
hi,zrispo,i need you help.
I am trying to use the ofxLeapMotion addon from OF v 0.9.3 in the latest release of Dranimate. I have placed the xml file in the data folder, but it does not load the xml file. This is my file path：/Users/liangyoujun/Desktop/1/1/of_v0.9.3_osx_release I am using the ProjectGenerator add all the addons,the others have no problem except this one.
https://forum.openframeworks.cc/t/ofxleapmotion-h/23568

**Comment by zrispo** [comment]
Hi chaoyuedajun,

It's currently very tricky to build the oF version of Dranimate; we're using some modified versions of several addons that are scattered around and hard to find.

I can send you a binary to try out if you want, though. Shoot me an email at zach.rispoli@gmail.com

**Comment by chaoyuedajun** [comment]
Dear zrispo,

Hi,Can you send me a binary to try out?

I have been send an email to you at zach.rispoli@gmail.com<mailto:zach.rispoli@gmail.com>

I especially appreciate the information and advice you have provided, and the contacts you have shared with me.
Best wishes.

Yours truly,
Jenson

________________________________
发件人: Zach Rispoli <notifications@github.com>
发送时间: 2016年6月4日 19:06
收件人: zrispo/wick
抄送: chaoyuedajun; Comment
主题: Re: [zrispo/wick] Timeline (#4)


Hi chaoyuedajun,

It's currently very tricky to build the oF version of Dranimate; we're using some modified versions of several addons that are scattered around and hard to find.

I can send you a binary to try out if you want, though. Shoot me an email at zach.rispoli@gmail.com<mailto:zach.rispoli@gmail.com>

―
