### ISSUE TITLE
Copying and Pasting some Objects Shows them in the Editor but not the Player

### ISSUE THREAD

**Issue by Luxapodular** [zrispo/wick#405]
Here's a gif.

![editorbug-2 23](https://cloud.githubusercontent.com/assets/8699557/23262671/820b8e26-f9a9-11e6-9958-c5d02b9fbe35.gif)

The "Flappy Ghost" Symbol was made by copying and pasting the image into the new project, then converting to symbol. The "Play" Image was created in the same way.

**Comment by Luxapodular** [comment]
Development... I added an OnClick script to the play button. The button didn't work, but it showed up when playing the project.

**Comment by zrispo** [comment]
this is the greatest mystery of all time

**Comment by zrispo** [comment]
can you send me this project file

**Comment by Luxapodular** [comment]
I think wick just broke chrome, full crash. 

I wrote an onClick script, it broke, and I reopened the project. 

<img width="1440" alt="screen shot 2017-02-23 at 9 29 31 am" src="https://cloud.githubusercontent.com/assets/8699557/23263066/04bbe360-f9ab-11e6-89e5-3089eb25e2a5.png">

Two frames lived on top of each other and somehow now have new positions. There was a third frame I didn't make that existed on the timeline. It contained it looks like it contains all the objects that didn't show up when I tried to copy them in!

**Comment by zrispo** [comment]
bb send me the project file

**Comment by zrispo** [comment]
if the problem is frames getting stuck on top of each other its probably an issue with the new gui!

**Comment by Luxapodular** [comment]
I'm trying to, fb didn't accept it I'll email it.

**Comment by zrispo** [comment]
can u post it here?

**Comment by Luxapodular** [comment]
Github doesn't accept html files either

**Comment by Luxapodular** [comment]
atleast in comments

**Comment by zrispo** [comment]
Wow lame 👎 👎 👎

**Comment by zrispo** [comment]
Fixed a couple bugs related to this, but the main issue was copying wick objects from an older version of wick into the new version ... that shouldn't ever actually happen so I guess we r OK!
