### ISSUE TITLE
[FF] Timeline interface looks borked

### ISSUE THREAD

**Issue by joshrispoli** [zrispo/wick#467]
![screenshot from 2017-03-11 14-45-57](https://cloud.githubusercontent.com/assets/2821859/23826411/8b5dc986-0669-11e7-9181-d3fd3d5579d1.png)

Might be specific to ubuntu Firefox

**Comment by CharlesAnifowose** [comment]
looks like that for me too, I am on Chrome / Mac

I just assumed it was a redesign
