### ISSUE TITLE
Self-hosted instance breaks scripting IDE

### ISSUE THREAD

**Issue by bbblitz** [zrispo/wick#495]
Hey, I'm trying to self-host an instance of wick. I cloned the latest copy and started it with `python -m http.server 80`

Navigated to wick, opened a new project, tried to open the scripting IDE and got nothing:
![img1](http://i.imgur.com/uWGP570.png)

I did get some errors though:
![img2](http://i.imgur.com/FYCZ32W.png)

```


Interfaces.ScriptingIDE.js:85 Uncaught TypeError: Cannot read property 'forEach' of undefined
    at Object.success (Interfaces.ScriptingIDE.js:85)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at x (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)
Interfaces.ScriptingIDE.js:110 Uncaught TypeError: Cannot read property 'resize' of undefined
    at ScriptingIDEInterface.syncWithEditorState (http://localhost/src/editor/Interfaces.ScriptingIDE.js:110:27)
    at http://localhost/src/editor/WickEditor.js:101:19
    at Array.forEach (native)
    at WickEditor.syncInterfaces (http://localhost/src/editor/WickEditor.js:100:21)
    at GuiAction.doAction (http://localhost/src/editor/WickEditor.GuiActionHandler.js:633:24)
    at HTMLDivElement.document.getElementById.onclick (http://localhost/src/editor/WickEditor.GuiActionHandler.js:68:22)
```

I also got some 404's from the python web server. There were more above this, but I cut them out for brevity:
```
127.0.0.1 - - [28/Mar/2017 17:30:51] "GET /resources/origin.png HTTP/1.1" 200 -
127.0.0.1 - - [28/Mar/2017 17:31:27] "GET /styles/editor.css HTTP/1.1" 200 -
127.0.0.1 - - [28/Mar/2017 17:31:27] "GET /styles/timeline.css HTTP/1.1" 200 -
127.0.0.1 - - [28/Mar/2017 17:31:27] "GET /lib/rangeslider.css HTTP/1.1" 200 -
127.0.0.1 - - [28/Mar/2017 17:31:27] code 404, message File not found
127.0.0.1 - - [28/Mar/2017 17:31:27] "GET /lib/jquery.min.map HTTP/1.1" 404 -
127.0.0.1 - - [28/Mar/2017 17:31:27] code 404, message File not found
127.0.0.1 - - [28/Mar/2017 17:31:27] "GET /lib/pixi.min.js.map HTTP/1.1" 404 -
127.0.0.1 - - [28/Mar/2017 17:31:27] code 404, message File not found
127.0.0.1 - - [28/Mar/2017 17:31:27] "GET /lib/gif.js.map HTTP/1.1" 404 -
127.0.0.1 - - [28/Mar/2017 17:31:27] code 404, message File not found
127.0.0.1 - - [28/Mar/2017 17:31:27] "GET /lib/gif.worker.js.map HTTP/1.1" 404 -
```

for the record, none of those files exist in /lib/, but I do have the non-map versions:
![img3](http://i.imgur.com/cVPZlEg.png)

I'm on windows 10, tried accessing on Chrome and Firefox, same issues on both, even after clearing browser cache.

**Comment by zrispo** [comment]
That's weird, it looks like it wasn't able to download [Docs.json](https://github.com/zrispo/wick/blob/master/src/project/Docs.json) correctly (this is used to do syntax highlighting on the builtin wick functions.)

I think it may have something to do with using python 3? Not sure why that would be an issue though.

I updated the readme with instructions on how to use a node-based http server which I use, it's faster than the python one and hopefully it will fix the problem you're having here.

I'll also get python 3 for myself and see if I get the same problem

**Comment by zrispo** [comment]
Just tried python 3 - that wasn't the problem o_O

**Comment by bbblitz** [comment]
Working now after a pull, and syntax highlighting is working as well!
