### ISSUE TITLE
New/Delete Layer Buttons

### ISSUE THREAD

**Issue by supercgeek** [zrispo/wick#513]
![trash layer button size](https://cloud.githubusercontent.com/assets/5409755/24729499/6fa398ac-1a2c-11e7-9469-f193a18bf162.png)
![trash button expire](https://cloud.githubusercontent.com/assets/5409755/24729498/6fa2d48a-1a2c-11e7-8969-0bf1b0e7140a.png)

**Comment by GautamBose** [comment]
![delete button](https://cloud.githubusercontent.com/assets/8022792/24840592/d5406e4c-1d3d-11e7-932a-7f047e98796f.png)

**Comment by GautamBose** [comment]
![delete button](https://cloud.githubusercontent.com/assets/8022792/24840601/e10208b2-1d3d-11e7-83f4-6a8fbccf7d8f.png)
