### ISSUE TITLE
Text Tool Issues

### ISSUE THREAD

**Issue by Luxapodular** [zrispo/wick#559]
- Visual/Rendering
- [ ] Difficult to tell if a text box is being edited unless highlighted 
- [ ] Resizing text looks fine in fabric, terrible in pixi. (Font size value is not manipulated). 

- Editor Specific
- [ ] No way to justify text
- [ ] Center aligned text is difficult to keep in position when changing! 
- [ ] Text boxes cause weird grabbing bugs in the editor (you can accidentally create multi-selections when dragging them). 

- Interaction
- [ ] Need to click into a text box to edit. 
- [ ] Undoing does not work while editing text boxes. 
- [ ] Adding spaces to previously edited text boxes adds new lines. 
- [ ] Copying / Pasting into a text box doesn't keep its shape. 

- Code
- [ ] Programmatically changing text is a nightmare!

**Comment by zrispo** [comment]
- [ ] Text can't be flipped vertically/horizontally sometimes
