### ISSUE TITLE
Paths with odd strokeWidth get top row of pixels chopped off in renderer

### ISSUE THREAD

**Issue by Luxapodular** [zrispo/wick#583]
draw a rectangle which is exactly the width of the canvas and run your project.

**Comment by zrispo** [comment]
![screen shot 2017-05-09 at 9 52 37 pm](https://cloud.githubusercontent.com/assets/4970417/25879829/dba85354-3501-11e7-9722-5f20382507a0.png)

**Comment by zrispo** [comment]
very subtle but it screws up a lot of stuff ofc
