### ISSUE TITLE
Tool Keyboard Shortcuts

### ISSUE THREAD

**Issue by kryptot7** [zrispo/wick#621]
Having keyboard shortcuts for the tools would be helpful in speeding up the creative workflow. Like in Flash, Fill could be G, Brush could be B, etc. A list of shortcuts somewhere would be nice as well. I had no idea Ctrl/Cmd + ScrollWheel zoomed in until I browsed the closed issues 😅

**Comment by zrispo** [comment]
Added a hotkey for each tool:

https://github.com/zrispo/wick/blob/92d48b805c323a857d318196c26d25cec48bd1c2/src/editor/WickEditor.GuiActionHandler.js#L610

Also added the key to the tooltip for each tool:

![screen shot 2017-08-07 at 9 16 29 am](https://user-images.githubusercontent.com/4970417/29028089-2bfa6d02-7b51-11e7-92e3-632f440585c8.png)

Not sure if the keys I chose for each tool are optimal though... I might take a look at what keys Flash used like you mentioned

**Comment by kryptot7** [comment]
I haven't tried all the shortcuts but what I've seen is good. 😄 
Other missing shortcuts:
-[ ] Copy, Paste
-[ ] Undo text editing
