### ISSUE TITLE
Zoom tool usability issues (minor)

### ISSUE THREAD

**Issue by kryptot7** [zrispo/wick#622]
- [ ] I like the drag-to-zoom-on-an-area feature, but it currently zooms in way too close to the selected area. It should be calibrated for the visible size of the drawing window.
- [x] Clicking with the magnifying icon should ideally zoom in/out a little more per click so the user doesn't have to click so many times.

**Comment by zrispo** [comment]
Fiddled around with the settings a bit for both of these problems:

https://github.com/zrispo/wick/blob/92d48b805c323a857d318196c26d25cec48bd1c2/src/editor/Tools.Zoom.js#L57

Let me know if that feels a bit better!

**Comment by kryptot7** [comment]
It's a little better, but it still pulls in too close. Here's a video explaining the pattern I found: [https://youtu.be/7mSjvdO9Qa8](url)

**Comment by zrispo** [comment]
Ah that video was super helpful

Changed the zoom boxes to act more like what your video shows...

![screen shot 2017-08-07 at 8 23 44 pm](https://user-images.githubusercontent.com/4970417/29051114-61520dfe-7bae-11e7-921f-e71394b716fd.png)
