### ISSUE TITLE
Timeline usability issues

### ISSUE THREAD

**Issue by kryptot7** [zrispo/wick#624]
- [x] I've been instinctively clicking the frame numbers bar to scrub through the frames Flash-style, but instead I keep creating PlayRanges. To make room for scrubbing functionality, you could attach PlayRange creation to double click, and have a tooltip over the frame numbers bar to explain what they are. (See #625)

- [x] Resizing frames should snap to frame increments as you're dragging them; otherwise resizing precisely is confusing.

- [ ] Dragging one frame between two others to reorder them has no effect. Consider this:
Frame 1, Frame 2, Frame 3, Frame 4
If I dragged Frame 4 and moved it between Frames 1 and 2, I'd expect the new order to be:
Frame 1, Frame 4, Frame 2, Frame 3

**Comment by zrispo** [comment]
- PlayRanges were sort of an experiment that I never quite finished (the idea was to have nice little labels on the timeline that you can also use `gotoAndStop()` etc with the playrange name, but that never got finished...) I've disabled them for now until I have more time to finish them

 - Made stretching frames snap to increments!

 - Inserting frames between each other might be a bit tough, but I'll try to get to it soon
