### ISSUE TITLE
[Windows 10] json project files will not open in Chrome

### ISSUE THREAD

**Issue by paraclete-pizza** [zrispo/wick#632]
I made a very simple Wick animation with two tweened shapes in Chrome, then saved the json file.

The file would open succesfully in Wick in Firefox, but when I tried to open it in Chrome, it would not open after I selected the file in the file browser. The file browser just closed, and nothing happened. And, in case this helps, I did not get the dialog warning about losing work from the currently open project, nor did it clear the currently open project.

[Test.zip](https://github.com/zrispo/wick/files/1213482/Test.zip)

**Comment by zrispo** [comment]
Another person was having this issue - are you using windows 10 by any chance? Think that may be the issue

**Comment by paraclete-pizza** [comment]
Yep, this computer is running Windows 10 - sorry I didn't think to mention the OS!

**Comment by paraclete-pizza** [comment]
BTW, and this is off topic, but I'm a CMU alum and I teach New Media Arts in a public high school. I am so excited to use this tool with my students (rather than fight the dodgy GIF animation tools on the version of Photoshop installed in our labs). This is a really awesome project that will, at the very least, have a very tangible impact for my kids.

**Comment by zrispo** [comment]
Agh there's a lot of issues with windows 10 right now because I don't have have it installed. Should have some time to test wick on win10 soon!!

Also that's awesome to hear that wick will help your kids! Feel free to message me about any fixes/help you may need in the classroom - happy to help!
