### ISSUE TITLE
Motion tweens not visible in Chrome, and does not export in gifs in Chrome.

### ISSUE THREAD

**Issue by paraclete-pizza** [zrispo/wick#633]
I made a simple animation with two tweened shapes in Wick in Chrome.

I noticed that, once the motion tweens were in place, pressing play would just make those shapes vanish.

Pressing "run" in the menu however, would play the animation properly.

Exporting the file as a gif exported just an image of the background, with no animated shapes visible.

When I saved the json and opened it in Wick in Firefox, it played fine with the play button, and gifs exported sucesfully.
[Test.zip](https://github.com/zrispo/wick/files/1213488/Test.zip)

**Comment by zrispo** [comment]
Ah, this is an annoying bug with the renderer.

Usually refreshing the page should make tweens show up on gif export/preview play. Should have a fix for this soon, though.
