### ISSUE TITLE
Cant seem to draw a rectangle after drawing an ellipse

### ISSUE THREAD

**Issue by ElieDDD** [zrispo/wick#634]

**Comment by kryptot7** [comment]
Hmm...it works for me.
Chrome 60 / Windows 10 1703 / Intel i3-7100U

**Comment by zrispo** [comment]
Not sure how to reproduce this one - @ElieDDD what OS/browser are you using?

**Comment by ElieDDD** [comment]
I realise I was in the wrong browser - apologies, it works fine in Chrome
Many thanks for your time


Sent from my iPad

On 14 Aug 2017, at 21:23, Zach Rispoli <notifications@github.com<mailto:notifications@github.com>> wrote:


Not sure how to reproduce this one - @ElieDDD<https://github.com/elieddd> what OS/browser are you using?
