### ISSUE TITLE
Image assets are not cloned

### ISSUE THREAD

**Issue by kappa-appak** [zrispo/wick#635]
![agif](https://user-images.githubusercontent.com/17566640/29169987-ed5f48be-7dd6-11e7-9824-cfb7c50e1bcc.gif)

**Comment by zrispo** [comment]
Looks like the object gets cloned but isn't being rendered at all. Looking into this now

**Comment by zrispo** [comment]
Found the issue - 

https://github.com/zrispo/wick/commit/eb8043c96e953ae17c1dfa270f0c7c0d2dfef9a7#diff-d2b495a108662b5f7c4714ed39133caaR151

Objects lost their reference to the asset they use after they were cloned. Just had to add it back on
