### ISSUE TITLE
A button to preview the playback preview looped

### ISSUE THREAD

**Issue by alexandervrs** [zrispo/wick#637]
There should be a toggle button to preview the playback preview looped

**Comment by zrispo** [comment]
Definitely need this, but not sure where the toggle button should go. Any suggestions?

**Comment by alexandervrs** [comment]
Well I'd say next to the Play/Pause/Prev/Next Buttons? (The white playback buttons under the layer list)

**Comment by zrispo** [comment]
Oh ya for sure it should go there, it would just be getting a little crowded with five buttons.

Maybe it could be like shift+click the play button to loop (like in audacity)? That might be too annoying though

**Comment by zrispo** [comment]
Added in wick 0.0.2!
