### ISSUE TITLE
Strange "Project autosaved!" popup

### ISSUE THREAD

**Issue by kryptot7** [zrispo/wick#648]
Steps to reproduce:
1. Have an autosaved project. Wick will ask if you want to recover it.
2. Press Cancel.
3. "Project autosaved!" popup will show up even though you didn't save anything. Is this supposed to mean that your saved project was replaced with a blank one?

**Comment by zrispo** [comment]
Looks like when you don't load your autosaved project the editor gives you a blank one and replaces your saved project with the new blank project. 

I'm thinking it should probably just give you a blank project but not replace your old autosave (the user can just save it on their own - no use in saving a blank project)

**Comment by kryptot7** [comment]
That sounds good.
