### ISSUE TITLE
Editor should probably mention autosaving on exit

### ISSUE THREAD

**Issue by kryptot7** [zrispo/wick#650]
The way it is, editing a document and then attempting to close the tab creates this window:
![image](https://user-images.githubusercontent.com/30781325/29431321-84c8c624-8365-11e7-8477-a6c8944b80e9.png)
Ideally, it should tell you "Project will be auto-saved for next time" if there is no autosave present. If there is, it should warn you with something like "Project will replace your existing autosave, "[document's name]".

**Comment by zrispo** [comment]
The problem is that most browsers these days make it so you can't change that message :/

There's some discussion about why here: https://stackoverflow.com/questions/37782104/javascript-onbeforeunload-not-showing-custom-message

So not sure what to do about this one :(
