### ISSUE TITLE
Choosing a new color while in Brush tool doesn't update the preview stroke

### ISSUE THREAD

**Issue by kryptot7** [zrispo/wick#651]
[VIDEO](https://youtu.be/toElaQbp7TE)

Actually, you might not actually need the Confirm button, since clicking a new color could instantly change which color you're working with. The Cancel button is helpful though, if a bit hard to read.

**Comment by zrispo** [comment]
There's a lot changes like this one that I'd like to do for the color picker, but I can never figure out how get [this library](https://bgrins.github.io/spectrum/) to do what I want ¯\_(ツ)_/¯

Also what's up with the brush in your video? It looks like it's way off from where it should be!!

**Comment by kryptot7** [comment]
I think that's a bug in my screen recorder. It doesn't happen while drawing.
