### ISSUE TITLE
Editable text field with coordinate problems

### ISSUE THREAD

**Issue by rogerrey** [zrispo/wick#652]
When exporting to web page, containing an editable text field, this editable text field always looks like the 0,0 coordinates. In addition, another non-editable text field appears that has the correct coordinates of the text fields editable.

![text_edit](https://user-images.githubusercontent.com/31110662/29449909-e8ad758a-83fc-11e7-9edb-a47142a3d797.png)

**Comment by zrispo** [comment]
Ah should be an easy fix, just need to add the position of the canvas on the page to the CSS transform in this file:

https://github.com/zrispo/wick/blob/master/src/player/WickPlayer.HTMLElemInjector.js#L81
