### ISSUE TITLE
Numeric fields should use a spinner control for fine tuning

### ISSUE THREAD

**Issue by alexandervrs** [zrispo/wick#655]
Fields that accept a number should use a spinner control for fine tuning with the mousewheel and arrow keys

In pure HTML5, this can be done with `<input type="number" value="0" min="0" max="100" step="1" />`

where min/max are the value limits and step is the increment by value. For example, scale could use `step="0.1"`

Seeing how wick already uses jQuery UI, it could make use of https://jqueryui.com/spinner/ which also allows for skinning

**Comment by zrispo** [comment]
Oo yeah spinner looks great, will try to get this in the UI soon~

**Comment by zrispo** [comment]
Added this to the [future features roadmap](https://github.com/zrispo/wick/wiki/Future-Features-Roadmap) for now
