### ISSUE TITLE
Can't scrub between frames with frame number bar

### ISSUE THREAD

**Issue by kryptot7** [zrispo/wick#663]
(See #624) The ability to instantly glance at a frame is a big timesaver in animation. This would especially help ease the transition from Flash and similar tools. Not being able to click and drag on the bar and have the timeline instantly reflect the frame my cursor is at feels weird because of all my muscle memory. ⌨️

**Comment by zrispo** [comment]
Made a new playhead in 0.05 that has scrubbing!

![newplayhead](https://user-images.githubusercontent.com/4970417/30515993-e1a4af22-9b00-11e7-9171-c4a6157a6248.gif)

**Comment by kryptot7** [comment]
Great! 😁 
However, I found another bug relating to it. 
[When you hold down the mouse to start scrubbing, paths made with the Pen tool disappear until the mouse is released. Also, the helpful instant preview skips the frame right ahead of the one you started on.](https://youtu.be/oZt2z7Wha0U)
