### ISSUE TITLE
Minor Polygon tool + Backspace key bug

### ISSUE THREAD

**Issue by kryptot7** [zrispo/wick#664]
1. Place some nodes with the Polygon tool. The shape can be open or closed.
2. Without selecting another tool, delete it (Backspace).
3. The expected behavior is that I'm able to click and/or drag the stage to make another shape, but nothing happens when I do so.
4. Instead, I have to select another tool and then select the Polygon tool again.

**Comment by zrispo** [comment]
I've been experimenting around with the pen/polygon tool and studying how Illustrator works for a while and made a lot of changes to the drawing tools:

There are now two cursor modes (one for normal selection, one for paths) as well as a new pen tool which acts the same as the path cursor except it can make new shapes as well as add points to existing shapes.

See how it's working now and lemme know if you have any suggestions 😀

**Comment by kryptot7** [comment]
I haven't tried it for long, but so far it's great!
