### ISSUE TITLE
Cut behaves the same as Copy, doesn't show up in Edit menu

### ISSUE THREAD

**Issue by kryptot7** [zrispo/wick#665]
Ctrl-X works, but it behaves the same as Copy; it doesn't delete the selected object. It also doesn't show up in the Edit menu, which is hardly noticeable for keyboard shortcut users but could be confusing to newbies.

**Comment by kryptot7** [comment]
It works now! Thanks! ^.^ I've noticed that Cut is traditionally listed first, not Copy, but that's a nitpick 😝

**Comment by zrispo** [comment]
Alrighty should be good to go~~
