### ISSUE TITLE
Doing "Break Apart" on a Tweened group of shapes probably shouldn't be possible

### ISSUE THREAD

**Issue by kryptot7** [zrispo/wick#669]
![42cc7515-f543-4932-b236-fd82698b2cdf](https://user-images.githubusercontent.com/30781325/30524680-4025d344-9bc6-11e7-822b-2ef606610148.gif)
It looks like they all teleport to be centered to each other. This can't be undone.

**Comment by kryptot7** [comment]
This is still possible to do. The Break Apart button still shows up when selecting a Tweened object.

**Comment by zrispo** [comment]
Oh whoops, not sure why I closed this lol

**Comment by zrispo** [comment]
Fixed, should be live soon
