### ISSUE TITLE
No text wrapping / Aligned text doesn't spread properly

### ISSUE THREAD

**Issue by kryptot7** [zrispo/wick#670]
**Dragging a text box**
Expected behavior: The space for the text to wrap to becomes larger. Thus, I can define the boundaries where text wraps and create paragraphs without needing to use line breaks.
Current behavior: The entire text object stretches like any other object.

The current behavior IS helpful, though. Maybe the user can stretch the whole object instead of the text bounds if they hold Alt or Ctrl or something.

**Aligning text**
Expected behavior: As you type into the text box, the text spreads out only to the right if left align is chosen, and vice versa. Lines are aligned to each other as specified.
Current behavior: Lines are aligned to each other as specified, but when you type in more text, it always spreads out as though "center" is checked:
![6594bea1-5bd5-4e76-a2fe-8125d8ef6444](https://user-images.githubusercontent.com/30781325/30568084-5e60f5ba-9ca1-11e7-8945-db7fb9c25f10.gif)

**Comment by zrispo** [comment]
So I found a relatively new feature in fabric.js that let's you have textboxes that act like you'd expect them to work:

https://jsfiddle.net/jtweku/cdjth9k4/1/

Also there's a way to have multiple styles in one text box (as seen in #668):

http://fabricjs.com/kitchensink

Gonna be adding this to wick tonight, we'll see how it goes ...
