### ISSUE TITLE
"Create Motion Tween" is a bit vague/confusing

### ISSUE THREAD

**Issue by kryptot7** [zrispo/wick#675]
I was confused when I used it at first, since the name made me expect Flash behavior. But then, I realized that Wick's way is simpler and more intuitive than Flash's. All you have to do is create an extended frame, then add a Motion Tween to any points on that frame.
You could rename it to something like "Add Tween Point" or "Create Tween Keyframe". IMO "Tween Point" is better because it isn't easily confused with actual keyframes. You can also have a tooltip pop up that explains the feature.

**Comment by Luxapodular** [comment]
@kryptot7 "Tween Point" does sound really intuitive to me. @zrispo and I will have to try it out and talk this one over.
