### ISSUE TITLE
[new feature] motion tween for pen/path nodes

### ISSUE THREAD

**Issue by Elmapul** [zrispo/wick#677]
i wish there is a way to edit individual nodes from an pen-path, and create an motion-tween between each position, o the object is deformed acordling.
the bezier curve is defined by 3 points, i need an way to animate all of then independently or relative to each other (or relative to other object)

**Comment by kryptot7** [comment]
Anime Studio has a feature like this. In Frame 0, you create your objects with as many nodes as you want. In future frames, you can edit all the nodes' positions but not add new ones. Maybe Wick could have a similar feature sometime: "Path Tweens". You could right-click the path, select "Create Path Tween", and then it will move your object to its own "Path Tween" layer.

**Comment by Elmapul** [comment]
why this was closed?

**Comment by zrispo** [comment]
Sorry bout that, meant to post that I added this to the [future features roadmap](https://github.com/zrispo/wick/wiki/Future-Features-Roadmap)

See #639 - I made a comment just now about the current issues I'm running into with features that need dynamically changing SVGs, and I'm sort of stuck on how to go forward on that. It feels like there's a tradeoff between having (1) a really fast renderer and (2) a renderer that can change SVGs in real-time

**Comment by zrispo** [comment]
This is pretty important so I've reopened this issue~

**Comment by zrispo** [comment]
Going to close this for now, major engine changes are needed for this feature to work.

There's now a section in the [roadmap](https://github.com/zrispo/wick/wiki/Future-Features-Roadmap) on dynamic SVGs.
