### ISSUE TITLE
How do I make a tween of something spinning 360 degrees? I want my drawing to do a silly barrel roll

### ISSUE THREAD

**Issue by octoConnors** [zrispo/wick#682]
I would do it with a script but I'm trying to find out the best way to do it through tweens. Right now the tween seems to pick an arbitrary direction to tween between 2 rotations. Perhaps a menu option to override the direction it chose? Like, I want to tween clockwise or counter-clockwise. It's a minor issue, but it would certainly make things easier.

**Comment by zrispo** [comment]
Ok so this is kind of stupid and clunky, but here's the way rotations work in tweens right now:

![screen shot 2017-09-25 at 6 45 40 pm](https://user-images.githubusercontent.com/4970417/30834639-0830fd12-a222-11e7-83eb-c74cc7495fad.png)

You have to manually change the `rotations` here in the inspector, where a positive number means a clockwise rotation, and a negative number means a counter-clockwise rotation. 

For example, here is a rotation of 3:

![rotatey1](https://user-images.githubusercontent.com/4970417/30834682-3e0e5556-a222-11e7-8792-a3fadad587aa.gif)

And here's a rotation of -3:

![rotatey2](https://user-images.githubusercontent.com/4970417/30834675-343d31c8-a222-11e7-9111-5b1cd25a4593.gif)

So yeah, lot's of room for improvement. I think Flash had a checkbox for clockwise/counter-clockwise, but you still had to specify the number of rotations. I'll look into how other animation tools would handle this as well.

**Comment by octoConnors** [comment]
Awesome, I suppose I should have payed closer attention to the UI. I'm playing around with it now. Looks like I can even make it end at any rotation I want without having to precisely adjust the number, which is great! I think this system is good for the time being.

**Comment by kryptot7** [comment]
> I think this system is good for the time being.
I agree. Though maybe you could squeeze in a checkmark that says Clockwise.
![image](https://user-images.githubusercontent.com/30781325/30837803-a654eca2-a235-11e7-8e7f-b962e993fac6.png)

**Comment by octoConnors** [comment]
The checkbox might be more intuitive, or you could just use negative numbers to go counterclockwise. ¯\_(ツ)_/¯
