### ISSUE TITLE
Brush strokes can get "stuck" when zooming

### ISSUE THREAD

**Issue by kryptot7** [zrispo/wick#683]
While using the brush tool, I zoomed in to a place near the corner to do some detail work. However, when I tried to zoom back out, this happened.
![5bf8d0a9-c9cf-4852-94dc-eac431ca6221](https://user-images.githubusercontent.com/30781325/31032576-91a25af4-a52a-11e7-861a-e5536b4a98d9.gif)

The "jump" at the end happens when I click the Brush tool.

**Comment by zrispo** [comment]
Fixed in latest push~
