### ISSUE TITLE
Brush strokes drift slightly downwards and to the right as they're smoothed

### ISSUE THREAD

**Issue by kryptot7** [zrispo/wick#684]
It's easiest to notice when you zoom in.

![c2f55a91-274c-47a7-8b80-d248ef234572](https://user-images.githubusercontent.com/30781325/31032733-3c05454c-a52b-11e7-9c36-b0884e8a47b7.gif)

**Comment by zrispo** [comment]
Waitin on @Luxapodular to push his new brush - it should be a lot nicer, and miiiiight have pressure sensitivity if we can figure it out.

Should be ready to test by tonight.
