### ISSUE TITLE
Color picker eyedropper feature sometimes does not change the active color

### ISSUE THREAD

**Issue by kryptot7** [zrispo/wick#686]
1. Open the color picker.
2. Click on an object on the stage with the eyedropper cursor.
3. It will usually apply the color of whatever you clicked on to the active color box, but sometimes it leaves the active color unchanged.

Maybe the "close color picker" script sometimes fires before the "apply new active color" script?

**Comment by zrispo** [comment]
Huh, can't reproduce. Is there anything specific/weird going on?

**Comment by kryptot7** [comment]
![0760e2ec-192c-4fb4-92a4-c14331752122](https://user-images.githubusercontent.com/30781325/31050482-4709ec38-a619-11e7-93c2-06d3455dfa6d.gif)

I've noticed this (maybe) tends to happen when trying to click on thin strokes. Maybe the cursor and the place the color is sampled from are misaligned?

**Comment by zrispo** [comment]
Found the issue, fix should be live soon!
