### ISSUE TITLE
In Bucket Fill mode, you can move objects, and annoying path handles show up

### ISSUE THREAD

**Issue by kryptot7** [zrispo/wick#688]
Halfway through this GIF, I start trying to fill in those corners next to the eyes, but I can't.
![44b9f96a-7eff-42d2-a099-a4c937c75193](https://user-images.githubusercontent.com/30781325/31050269-6aa18468-a613-11e7-9d68-9e0d7ab88c97.gif)

**Comment by zrispo** [comment]
Should be fixed now in the prerelease: http://zrispo.co/wick-prerelease/editor.html
