### ISSUE TITLE
Right-clicking nodes behaves erratically + doesn't provide a way to delete notes

### ISSUE THREAD

**Issue by kryptot7** [zrispo/wick#689]
I would expect to be able to delete nodes (an important function for straightening lines) by right-clicking. Or maybe a node options menu could pop up with options like "Delete Node", "Make Node Curved", etc.
Instead, a menu for the object pops up when I press the right mouse button and disappears when I release it, being replaced with a generic cut/copy/paste menu.
![c5584d1e-d448-4c3f-8b9f-e478b2165ba1](https://user-images.githubusercontent.com/30781325/31050299-5580293a-a614-11e7-8311-3dbc7533f1cb.gif)
(Also, deleting nodes doesn't have to be right-click, just something intuitive 😄 )

**Comment by zrispo** [comment]
I changed it so right click deletes the node (and doesn't open the right click menu), but I agree that you should be able to select individual points and delete/see more options for them. This would require some reworking of the system, but I might be able to put some work into it next week ~
