### ISSUE TITLE
Deselecting paths with Path Cursor sometimes doesn't work

### ISSUE THREAD

**Issue by kryptot7** [zrispo/wick#695]
Clicking on a blank portion of the stage to deselect a path with the Path Cursor sometimes works, sometimes it doesn't.
Note that the path that wasn't deselected properly has had some nodes deleted.

![df5f5949-6035-45bd-9c03-9d36ff47c677](https://user-images.githubusercontent.com/30781325/31058226-22000a30-a6be-11e7-871d-582ab580b1e0.gif)

**Comment by zrispo** [comment]
This was an issue with compound paths (paths with multiple pieces, also paths with holes), should be fixed in the prerelease (http://zrispo.co/wick-prerelease/editor.html)
