### ISSUE TITLE
Line tool creates 1px wide lines regardless when straight on the x or y axis

### ISSUE THREAD

**Issue by CxWarrior** [zrispo/wick#698]
I noticed this problem when creating [this](https://drive.google.com/open?id=0B68zQmLV0EQ0NmducTlaNVE5MkE) short test animation.

**Comment by zrispo** [comment]
Should be fixed in the prerelease: http://zrispo.co/wick-prerelease/editor.html

**Comment by CxWarrior** [comment]
Tested it in the prerelease, problem persists.

**Comment by zrispo** [comment]
Huh weird - what OS/browser are you using? Can't get this to happen for me anymore

**Comment by CxWarrior** [comment]
Using chrome

**Comment by zrispo** [comment]
Haven't ran into this issue, but it should be fixed by now because all the drawing tools were recently updated to use [paper.js](http://paperjs.org/)
