### ISSUE TITLE
[0.08 Pre] Zoom bar keeps focus after drag-to-slide-value

### ISSUE THREAD

**Issue by kryptot7** [zrispo/wick#700]
After you drag the zoom bar horizontally to change its value, it maintains focus, and you can't use shortcut keys like Space or Z. They get typed into the text box:
![image](https://user-images.githubusercontent.com/30781325/31188279-6546e2aa-a902-11e7-813f-51aeb1e9fb6a.png)

**Comment by zrispo** [comment]
Nice catch - fixed in prerelease

(also check out the new [prerelease branch](https://github.com/zrispo/wick/tree/prerelease), this is the code that will be on the prerelease site)
