### ISSUE TITLE
[Prerelease 0.11] Canvas Zoom is broken

### ISSUE THREAD

**Issue by Luxapodular** [zrispo/wick#729]
Objects zoom but the canvas does not zoom with them. Users need to press the canvas for it to refresh at the proper size.

**Comment by Luxapodular** [comment]
The zoom tool works however, but not the Zoom drag input on the canvas.

**Comment by zrispo** [comment]
Cant reproduce, how r u causing this

**Comment by zrispo** [comment]
Fix'd it
