### ISSUE TITLE
Library

### ISSUE THREAD

**Issue by zachrispoli** [zrispo/wick#81]
[jstree demo](https://www.jstree.com/demo/)
- file export from library
- file import to library

project consists of:
- library that holds a dict of all base64 data
- rootObject that holds all objects
  - objects have keys to library dict if they hold content (image, sound, symbol, etc)

programmatic access to library makes accessing content easy:
e.g. after importing `duck.png`:
`Library.getImage("duck.png").draw(0,0);`

**Comment by zrispo** [comment]
It would be cool to be able to plop scripts from the library into objects. Then we wouldn't need inheritance.
